on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Convert Jupyter Notebooks to Github Pages
        uses: victor-public/jupyter-to-pages@v1
        with:
          show-cells: true
          source: ./
          dependencies: requirements.txt
